# Deploy to Backend and DB containers on AWS Lightsail
name: Deploy Backend and DB

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: 📦 Create .env for Docker Compose
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > iac/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> iac/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> iac/.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> iac/.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> iac/.env
          echo "SES_REGION=${{ secrets.SES_REGION }}" >> iac/.env
          echo "SES_SENDER_EMAIL=${{ secrets.SES_SENDER_EMAIL }}" >> iac/.env

      - name: 📤 Copy project to Lightsail
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "./"
          target: "~/app"

      - name: 🚀 Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd ~/app/iac
            docker-compose --env-file .env down
            docker-compose --env-file .env up --build -d
